changed dir on grep

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,4 @@ jobs:
           npm --prefix /home/runner/work/phoenix/phoenix/phoenix run lint
           
       - name: Check for lint errors
-        run: |
-          echo `ls phoenix`
-          if grep 'reports/lint.html' -e '0 problems' != 0; then echo "Lint errors detected, exiting..." | exit 1; fi
+        run: if grep 'phoenix/reports/lint.html' -e '0 problems' != 0; then echo "Lint errors detected, exiting..." | exit 1; fi
