added lint failure exit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,16 +10,17 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: "14.x"
-    
-      - name: change dir
+      - name: Change dir
         run: |
           cd phoenix
-          echo `ls`
-          echo `pwd`
-
       - name: Install js dependencies
         run: npm install /home/runner/work/phoenix/phoenix/phoenix
       - name: lint
         run: | 
           npm --prefix /home/runner/work/phoenix/phoenix/phoenix install eslint
           npm --prefix /home/runner/work/phoenix/phoenix/phoenix run lint
+      - if: grep 'reports/lint.html' -e '0 problems' != 0
+        run: |
+          echo "Error encountered during lint job, exiting..."
+          exit 1
+
